### PR TITLE
fix fight to the last so it saves against burn

### LINKED ISSUE #3032: Fight to the Last doesn't save from burn
Hey pals, thanks for all you do for this site!

Just had a game where I didn't get a prompt to use the Fight to the Last in my hand to save from a Drogon (IDP) trigger, which should work as the save sets STR to 1, preventing immediate death from terminal burn. A spectator said they'd found it wasn't implemented properly either. Seems to be fine for other methods of death.

### PR DESCRIPTION
**Pull request by EvadLhorg**
resolves #3032

### CODE REVIEW

File: server/game/cards/15-DotE/FightToTheLast.js [hunk 1]
```diff
@@ -6,14 +6,15 @@ class FightToTheLast extends DrawCard {
...
+                onCharacterKilled: event => (event.allowSave || event.isBurn) && event.card.canBeSaved() && event.card.controller === this.controller
             },
             location: 'hand',
             handler: context => {
                 context.event.saveCard();
+                let savedCard = context.event.card;
                 if(context.event.card.kneeled && context.event.card.allowGameAction('stand')) {
                     this.game.resolveGameAction(
-                        GameActions.standCard(context.event.card),
+                        GameActions.standCard(() => ({ card: savedCard })),
```
Comment (ystros) [inline server/game/cards/15-DotE/FightToTheLast.js:17]: Good catch, surprised no one has complained about this portion before.
