### PR TITLE
fix the seed is strong so it actually discards the chosen card

### LINKED ISSUE #3402: Double The Seed is Strong (aHaH) wrong interaction
As pointed out by KaiRong [here](https://discord.com/channels/793188949144764447/853644798706450472/1135312156624163018), a situation happened where the Seed is Strong didn't worked.

### PR DESCRIPTION
**Pull request by EvadLhorg**
fixes #3402

### CODE REVIEW

File: server/game/cards/23-AHaH/TheSeedIsStrong.js [hunk 1]
```diff
@@ -35,7 +35,7 @@ class TheSeedIsStrong extends DrawCard {
 
     onCardSelected(context, card) {
         this.game.addMessage('{0} discards {1} from their {2}', context.event.winner, card, card.location);
-        GameActions.discardCard({ card });
```
Comment (ystros) [inline server/game/cards/23-AHaH/TheSeedIsStrong.js:38]: We should probably prefer to use game actions, rather than revert to the methods on the Player class. You should just be able to pass the game action to `this.game.resolveGameAction(...)` here.

**Review by ystros — CHANGES_REQUESTED** [review]
