### PR TITLE
fix Drogon's reaction is prompted only if there is at least one killa…

### LINKED ISSUE #3389: Drogon's reaction should be prompted only if there is at least one killable character
As pointed out by .mak [here](https://discord.com/channels/793188949144764447/853644798706450472/1121137562308853911), Drogon's reaction is prompted even if defending player has no characters with STR <= 1 to kill.

### PR DESCRIPTION
**Pull request by LaranSoft**
Close #3389

A simple conversion from handler to gameAction made the job :)

### CODE REVIEW

File: server/game/cards/15-DotE/Drogon.js [hunk 1]
```diff
@@ -11,13 +12,11 @@ class Drogon extends DrawCard {
             when: {
                 afterChallenge: event => event.challenge.winner === this.controller && this.isAttacking()
             },
-            handler: context => {
-                let characters = this.game.currentChallenge.defendingPlayer.filterCardsInPlay(card => card.getType() === 'character' && card.getStrength() <= 1);
-                this.game.killCharacters(characters);
-
-                this.game.addMessage('{0} uses {1} to kill all characters {2} controls with STR 1 or lower',
```
Comment (ystros) [inline server/game/cards/15-DotE/Drogon.js:18]: Need to convert this to use `message`. Currently, no message will be printed anymore.

**Review by ystros — CHANGES_REQUESTED** [review]
Looks good other than the missing messsage!
