### PR TITLE
fix the azor ahai reborn bug

### LINKED ISSUE #2731: Azor Ahai Reborn participation
Hello,

Stannis has Azor Ahai Reborn, Acolyte is initiating a challenge which makes him paticipate, then the acolyte is killed by Robert Strong and Stannis should not participate any more, though he does. Seems like a bug. See screenshot.

Sergey
Bug

### PR DESCRIPTION
**Pull request by EvadLhorg**
that stannis is still participating in a challenge even though the last rhllor character was removed

fixes #2731

### CODE REVIEW

**Comment by EvadLhorg** [comment]
The current fix to AzorAhaiReborn is not yet fully functional. If Stannis and another R'hllor character are declared as attackers in a challenge and the other R'hllor character is removed, Stannis will also be removed, which is wrong.

File: server/game/effects.js [hunk 1]
```diff
@@ -114,13 +114,18 @@ const Effects = {
                 let challenge = context.game.currentChallenge;
                 if(card.canParticipateInChallenge() && !challenge.isAttacking(card)) {
                     challenge.addAttacker(card);
-                }
+                    card.consideredToBeAttackingWasApplied = true;
+                    context.game.once('afterChallenge', () => {
```
Comment (ystros) [inline server/game/effects.js]: I think this would actually work, but there are some bad interactions from the effect engine. Since the effect has a `condition`, I think the engine will continually `unapply` and then re-`apply` the effect. So this event handler will be created more than once. Which in terms of what it's doing is fine - worst case the flag is set to `false` multiple times. It could be bad in terms of introducing an unintended number of event listener - I'm not sure whether there are implications in Node for that.

The alternate solution is to record which characters were declared on the `Challenge` class itself, and check that instead of adding this flag. Even doing that, though, there are edge cases - declare Azor Stannis and another R'hllor character, remove Azor Stannis from the challenge. Even though he was declared, since he was removed, Azor Ahai should make him participate again.
